import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// === Font setup ===
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// === Metadata dengan favicon PNG ===
export const metadata: Metadata = {
  title: "Albert Sumedha KT Portofolio",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",       // favicon.png ada di folder public
    shortcut: "/favicon.png",   // opsional untuk beberapa browser
    apple: "/favicon.png",      // opsional untuk perangkat Apple
  },
};

// === Root layout ===
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
